### ISSUE TITLE
Reimplement with RPC under the hood

### ISSUE THREAD

**Issue by e9t** [e9t/konlpy#1]
To overcome compatibility issues among OSs.
Some options:

- [Python XML-RPC Library](https://docs.python.org/2/library/xmlrpclib.html)
- JSON-RPC

or 

- [SWIG](http://stackoverflow.com/a/1119884/1054939)
- [GCJ](https://gcc.gnu.org/java/)
- [GCC](https://lucene.apache.org/pylucene/jcc/install.html)

**Comment by e9t** [comment]
JPype가 2014년 말을 기점으로 꽤 reliable해져서 그대로 써도 될 것 같습니다.

**Comment by minhoryang** [comment]
gRPC를 사용하는 KoNLPy를 만들어보고있습니다.
https://github.com/minhoryang/konlpy-gRPC
