### ISSUE TITLE
pip으로 JPype1 설치시 ValueError: [u'path', u'include', u'lib'] 및 exit status 2 오류 발생

### ISSUE THREAD

**Issue by hank110** [e9t/konlpy#38]
윈도우에서 pip으로 konlpy 설치 이전에 jpype1 설치시
`ValueError: [u'path', u'include', u'lib']` 에러가 발생합니다. 
http://bugs.python.org/issue7511과 비슷한 상황입니다.

여기서 나온 얘기처럼 Microsoft Visual Studio를 설치한 후 `pip install JPype1`을 해봤는데 이번에는 
`/cl.exe failed with exit status 2`라는 오류가 발생했습니다.
하지만 파이썬 쉘에서 KoNLPy 패키지를 실행해보면 작동하는 것으로 봐서 유의미한 에러인지는 모르겠네요.

**Comment by e9t** [comment]
안녕하세요. 문제 상황을 잘 설명해주셔서 감사합니다.
혹시 사용하시는 윈도우와, 파이썬, 및 KoNLPy, JPype1 패키지 버젼들을 알려주실 수 있나요?

**Comment by hank110** [comment]
윈도우 7, python 2.7.7, JPype1 0.5.4.2.win‑amd64‑py2.7.exe 사용했습니다.
근본적인 문제해결은 아닐수도 있으나
python을2.7.9로 다시 설치하니 이 문제가 해결됬습니다.

**Comment by e9t** [comment]
조만간 KoNLPy 0.4.0을 릴리즈하면서 문서에 업데이트 하겠지만, JPype1의 경우 2014년 말 0.5.7 버젼이 릴리즈 되었고 최근 Christoph Gohlke의 Window binaries도 업데이트 되어서 훨씬 편하게 설치하실 수 있습니다.

- http://www.lfd.uci.edu/~gohlke/pythonlibs/#jpype

위 링크에서 64비트 윈도우를 쓰시는 경우 `JPype1‑0.5.7‑cp27‑none‑win_amd64.whl`,
32비트 윈도우를 쓰시는 경우 `JPype1‑0.5.7‑cp27‑none‑win32.whl`를 다운로드 하시면 되고,
다운 받으신 `.whl` 파일은 pip을 이용해서 다음과 같이 설치하실 수 있습니다.

    $ pip install wheel
    $ pip install /path/to/JPype1‑0.5.7‑cp27‑none‑win_amd64.whl

**Comment by Seondong** [comment]
konlpy가 잘 설치되었는데 jpype때문에 import error가 났는데, 해결되었네요
잘 보고 갑니다~

**Comment by seanie12** [comment]
pip install JPype1-0.6.1-cp35-none-win_amd64.whl 이라 하면
![ad](https://cloud.githubusercontent.com/assets/19561061/15522738/79664b9e-224f-11e6-94d4-092cef90b64c.png)
이런 화면이 뜨네요 ㅠㅠ

**Comment by seanie12** [comment]
직접 Jpype 파일을 받아서 실행하면 이렇게 나오고요 ㅠㅠ
![default](https://cloud.githubusercontent.com/assets/19561061/15522774/b029e73a-224f-11e6-8434-eb1d82a74a85.png)

**Comment by cruishin** [comment]
JPype1-0.6.1-cp35-none-win_amd64.whl의 path가 잘못 된 것 같습니다. 디렉토리를 현재 디렉토리로 옮겨서 install 해 보시는건 어떨까요?

**Comment by seanie12** [comment]
Cd디렉토리 해서 파일이 위치한곳에서 하시란 말씀인거죠?

**Comment by Swalloow** [comment]
`JPype1-0.6.1-cp27-none-win_amd64.whl` 파일을 다운받으면
지원하지 않는 플랫폼이라는 오류 메세지가 출력됩니다. 
`JPype1-0.6.1-cp35-none-win_amd64.whl` 파일을 다운받아서 해결했습니다.
